# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nb',
                'doc_host': 'https://NoelJacob.github.io',
                'git_url': 'https://github.com/NoelJacob/nb',
                'lib_path': 'nb'},
  'syms': {'nb.core': {'nb.core.foo': ('core.html#foo', 'nb/core.py')}}}
